name: tabmat
channels:
  - conda-forge
  - nodefaults
dependencies:
  - libblas>=0=*mkl
  - pandas

  # development tools
  - black
  - flake8
  - numpydoc
  - pip
  - pre-commit
  - pytest
  - pytest-xdist
  - setuptools_scm

  # build tools
  - c-compiler
  - cxx-compiler
  - cython
  - jemalloc-local
  - make
  - mako
  - mkl-include
  - xsimd

  # documentation dev
  - jupyterlab
  - jupytext
  - matplotlib-base
  - seaborn-base
  - sphinx=3.5.3
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
