name: tabmat
channels:
  - conda-forge
  - nodefaults
dependencies:
  - libblas>=0=*mkl
  - formulaic>=0.6
  - numpy
  - pandas
  - polars
  - scipy

  # development tools
  - click
  - numpydoc
  - pip
  - pre-commit
  - pytest
  - pytest-xdist
  - ruff
  - setuptools_scm

  # build tools
  - c-compiler
  - cxx-compiler
  - cython !=3.0.4
  - make
  - mako
  - mkl-include
  - xsimd <11|>12.1

  # documentation dev
  - jupyterlab
  - jupytext
  - matplotlib-base
  - seaborn-base
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
