name: CI - Windows
on:
  push:
    branches:
      - main
jobs:
  windows-ci:
    name: "Win - tests - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: windows-latest
    env:
      CI: True
    strategy:
      fail-fast: true
      matrix:
        PYTHON_VERSION: ['3.7']
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: conda-incubator/setup-miniconda@3b0f2504dd76ef23b6d31f291f4913fb60ab5ff3
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          miniforge-variant: Mambaforge
          miniforge-version: 4.10.3-6
          use-mamba: true
          environment-file: environment-win.yml
          activate-environment: tabmat
      - name: Run Unit Tests
        shell: pwsh
        run: |
          python -m pip install -e . --no-deps -vv --no-use-pep517 --disable-pip-version-check
          pytest tests -m "not high_memory" --doctest-modules src/
